### ISSUE TITLE
where is ISIS 1.12?

### ISSUE THREAD

**Issue by amreladawy** [estatio/estatio#27]
The estatio pom requries ISIS 1.12 but it is not on the central Repo

`<isis.version>1.12.0-SNAPSHOT</isis.version> `

**Comment by danhaywood** [comment]
It depends on 1.12.0-SNAPSHOT, not 1.12.0.  There is a difference: -SNAPSHOT indicates work-in-progress, not yet released.  We do occasionally push out snapshot releases, but you can always also just build Isis from source; details at http://isis.apache.org/guides/cgcon.html#_cgcon_building-isis

**Comment by amreladawy** [comment]
Can I change it to 1.11.0   ?

**Comment by danhaywood** [comment]
Yes, that should work.  Actually, 1.11.1 is the latest release.
