### ISSUE TITLE
Q: What is the most suitable AS for estatio?

### ISSUE THREAD

**Issue by amreladawy** [estatio/estatio#28]
Given a limited CPU and memory, what is the most best AS to run estatio with minimum Memoryand CPU.

I like to run it on JBoss actually (WildFly as JDK8 is used) , but I think estatio requires less resource consuming AS. 
Maybe Tomcat or Jetty. 

What is recommended?

**Comment by danhaywood** [comment]
We run Estatio on a Tomcat server in production.  @jcvanderwal will be able to say how much memory we allocate; I think it's about 1G.  I don't see any reason not to run it on WildFly, though you'll need to disable CDI scanning.  See http://stackoverflow.com/questions/34311775/deploying-apache-isis-on-wildfly for some further details.

**Comment by jcvanderwal** [comment]
Minimum requirement for Estatio is 2GB, in production we use 4GB linux
virtual machines.

**Comment by amreladawy** [comment]
4GB? that is expensive VM.

What about Tomcat version? 8.0 ?

**Comment by jcvanderwal** [comment]
The 4GB is needed because we run a version with Apache Camel embedded. And
we own the hardware so memory is cheap. We currently run Estatio on Tomcat7
but migrate to Tomcat8 later this week. We have other Isis applications
that already run on Tomcat8.
