### ISSUE TITLE
Q:Some compilation errors in Eclipse, however maven build works fine

### ISSUE THREAD

**Issue by amreladawy** [estatio/estatio#29]
I imported the source code in eclipse. I see many compilation errors. For example

The class 
org.estatio.dom.budgeting.budget.Budget

the method following methods are not defined. 
getItems(), getProperty() 

And so many other similar cases.

Still mavn works and I was able to run the app in standalone mode. 

Any idea how to fix these compilation issues?

**Comment by danhaywood** [comment]
Sounds like the project didn't import correctly. Try using maven>update
project. I think there's some guides on the Isis website with more hints
/suggestions.

**Comment by amreladawy** [comment]
I tired update several times, from command prompt and from eclipse. 
For the class `org.estatio.dom.budgeting.budget.Budget`
The two missing methods are not in the class not up to any super. 

Also this is not compiling 
 `getLeaseTerm().getAuditedTurnover()`

**Comment by danhaywood** [comment]
Um, well if it builds from the command line but not in the IDE then the
issue must be in the project import somewhere or other. We've all moved
over to using IntelliJ, which we find (having got used to its own quirks)
to generally be more reliable. Perhaps you might try that out,  also?

**Comment by amreladawy** [comment]
I understand your point.
Just for the sake of integrity. The type `LeaseTermForTurnoverRent `should have the method `getAuditedTurnover() 
`

Where can I find it? 

This is only defined in the type  `LeaseTermForTurnoverRentLineItem`

**Comment by jcvanderwal** [comment]
We use Lombok [1] to reduce boilerplate and annotate private fields with
@Getter and @Setter which magically creates getters and setters behind the
scenes.

[1] https://projectlombok.org/

**Comment by amreladawy** [comment]
Wow, first time to heat about lombok. 

Why Not using Groovy for such thing (Getters and Setters)?

I think that README.MD should be updated to install lombok.  Even if IntelliJ is used.
