### ISSUE TITLE
The map view (gmap3) does not work without a little change

### ISSUE THREAD

**Issue by kodpraktikanten** [estatio/estatio#3]
Hi.

The map view (gmap3) does not work in the current snapshot. If I do a little change in the "isis.properties" file then it seems to work. I just added the package path for the wicket addons.

Changed from:
```
isis.services-installer=configuration-and-annotation
isis.services.ServicesInstallerFromAnnotation.packagePrefix=org.estatio,\
                                                            org.isisaddons.module
```
Changed to:
```
isis.services-installer=configuration-and-annotation
isis.services.ServicesInstallerFromAnnotation.packagePrefix=org.estatio,\
                                                            org.isisaddons.module,\
                                                            org.isisaddons.wicket
```

Regards

**Comment by martin-g** [comment]
I can confirm that the Map view doesn't work but adding this line doesn't seem to help for me.
Clicking on any marker in the map doesn't trigger Ajax http request.
Debugging...

**Comment by martin-g** [comment]
The problem I was hitting is fixed with https://git-wip-us.apache.org/repos/asf?p=isis.git;a=commitdiff;h=1232a0d6;hp=f49349d805fbd16f2bd2dbb51c1b3a50b3e58d1e.
Now GMap3 module works fine again here.

**Comment by kodpraktikanten** [comment]
Sorry, I had a copy of Estatio that had gone a bit dirty. In that copy the maps did not even show up. 

After cloning a a fresh copy of Estatio the maps are shown but clicking on any marker does not trigger anything. This seems to be what martin-g has pointed out a fix for.

**Comment by kodpraktikanten** [comment]
This seems not to be an issue any longer. Thanks for the help!

**Comment by danhaywood** [comment]
I've been working on releasing the 1.8.0 versions of all the isisaddons over the last day or two; I'll update Estatio later on this afternoon to use released versions rather than -SNAPSHOT.
