### ISSUE TITLE
problem installing estatio

### ISSUE THREAD

**Issue by malamalilu** [estatio/estatio#30]
can someone show me how to easily install estatio. i always get problems try to install and use it. hope to hear from you soon.

**Comment by danhaywood** [comment]
Well, 'mvn clean install' will generate a war Inn the webapps module's
'target' directory. which can then be deployed to Tomcat.

The Isis website has details about how to externalize configuration so that
you can then run against an external database etc.

What have you tried so far?

**Comment by malamalilu** [comment]
when ever i run mvn clean install, i got an error during compiling, later i request a estatio compile war file from jeroen. when i run it in tomcat, still not working

can i run estatio without using apache isis?

**Comment by danhaywood** [comment]
We run a (private) Jenkins CI for Estatio, so we are pretty certain it does
compile... :-)  It requires Java 8 to build.

To answer your question, no, Estatio cannot be run without Apache Isis.

**Comment by malamalilu** [comment]
Ok, i know how to run .war file in apache tom cat. i know where to put the estatio.war in apache tom cat. please where should i put the apache isis and what is the configuration when it comes to working it with estatio and how to configure estatio to run on mysql database?

**Comment by danhaywood** [comment]
> please where should i put the apache isis and
>

Estatio runs on top of Apache Isis - in other words it includes Apache
Isis' JAR files - so there is nothing extra to do.  If you look in the
standard WEB-INF/lib directory you'll see all the isis JAR files there.



> what is the configuration when it comes to working it with estatio and how
> to configure estatio to run on mysql database?
>
>
Coincidentally there's someone else also looking to run Estatio on MySQL;
forewarning that he hit an issue, see

https://github.com/estatio/estatio/issues/32

and also my reply.
