### ISSUE TITLE
theme issues

### ISSUE THREAD

**Issue by padrian** [estatio/estatio#44]
I have succesfully installed Estatio, but the display is terrible, i think it cannot reach the css files.

Hw do i trouble shoot. Cannot seem to find documentation !

Regards

**Comment by danhaywood** [comment]
We now that one of the themes, Amelia, is broken.  Haven't got around to
fixing it.  You can force the themes by configuring Isis itself, as per
[1].  Try "flatly" for example ... that's the one I like to use.

Fingers crossed...


[1] http://isis.apache.org/guides/ugvw.html#_ugvw_configuration-properties

**Comment by padrian** [comment]
thanks for the prompt response.

i used the simplex theme.
It is a good system. Do you offer paid support i have a client who needs a system like this.
Problem i find alot of bugs. Do you offer paid support or can u suggest to me some alternatives that perform a similar taskset as estatio and solve a similar problem i.e flexible property management.

Kindest Regards.

**Comment by danhaywood** [comment]
Is your problem now solved?  Was "simplex" the cause of the problem, or is
it the solution?

As for paid support, it's not in our plans to deliver Estatio as packaged
software... we think that every business will want and require its own
custom software.  We are (and have started) to pull out reusable building
blocks from Estatio, see catalog.incode.org, also isisaddons.org; we expect
other similar systems to reuse some of these building blocks.

If you'd like us to help you or your client become self-sufficient in Isis
so you can build/develop/maintain your own app, then we'd be happy to
oblige.  Or, if you'd like us to help you build such an app for you, we
could also do that.

Probably best to continue via email; danhaywood<at>incode.org will get to
me.
