### ISSUE TITLE
Default Data

### ISSUE THREAD

**Issue by padrian** [estatio/estatio#45]
How do i load default data.

I would like to test some of he functionality 

Regards

**Comment by johandoornenbal** [comment]
Hi,
One way would be by using the app manifest with the demo fixtures (https://github.com/estatio/estatio/blob/master/estatioapp/app/src/main/java/org/estatio/app/EstatioAppManifestWithDemoFixture.java)
Another way would be to use the menu: prototyping - run fixture script and choose "estatio demo fixture".

The use of app manifest is explained in https://isis.apache.org/guides/ugfun.html#_running_with_fixtures

Maybe you can sign up to our userlist and ask your questions there? By searching the list you can find a lot of information as well. (http://isis.apache.org/support.html)

Best regards,

Johan

**Comment by jintonghuoya** [comment]
I found the following error.
![image](https://user-images.githubusercontent.com/11802095/34868016-5cca240c-f7bd-11e7-8946-41af345f1246.png)

Regards
