### ISSUE TITLE
Estatio build fails

### ISSUE THREAD

**Issue by jullimullins** [estatio/estatio#50]
Hello!

I tried to build Estatio on raspberry Pi2 but the build fails with following error message. Any ideas how to successfully compile estatio? 

[INFO] Building Estatio (Open Source) DOM & Services 1.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Estatio (Open Source) ............................. SUCCESS [3.081s]
[INFO] Estatio (Open Source) UDO DOM - Agreement ......... SUCCESS [5.408s]
[INFO] Estatio (Open Source) UDO Base .................... SUCCESS [34.742s]
[INFO] Estatio (Open Source) UDO DOM - Tax ............... SUCCESS [0.588s]
[INFO] Estatio (Open Source) UDO Charge DOM .............. SUCCESS [0.442s]
[INFO] Estatio (Open Source) UDO DOM - Currency .......... SUCCESS [0.417s]
[INFO] Estatio (Open Source) UDO DOM - Geography ......... SUCCESS [0.388s]
[INFO] Estatio (Open Source) UDO DOM - Invoice ........... SUCCESS [0.494s]
[INFO] Estatio (Open Source) UDO DOM - Numerator ......... SUCCESS [0.399s]
[INFO] Estatio (Open Source) UDO DOM - Party ............. SUCCESS [0.385s]
[INFO] Estatio (Open Source) Canonical ................... SUCCESS [11.819s]
[INFO] Estatio (Open Source) DOM & Services .............. FAILURE [0.025s]
[INFO] Estatio (Open Source) Fixtures .................... SKIPPED
[INFO] Estatio (Open Source) App ......................... SKIPPED
[INFO] Estatio (Open Source) Integration Tests ........... SKIPPED
[INFO] Estatio (Open Source) Webapp ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:01.256s
[INFO] Finished at: Sun Jul 10 12:16:27 EEST 2016
[INFO] Final Memory: 26M/70M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.isis.tool:isis-maven-plugin:1.13.0-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.isis.tool:isis-maven-plugin:jar:1.13.0-SNAPSHOT: Could not find artifact org.apache.isis.tool:isis-maven-plugin:pom:1.13.0-SNAPSHOT -> [Help 1]

Someone has similar problem with apache ISIS simpleapp:
http://mail-archives.apache.org/mod_mbox/isis-users/201605.mbox/%3CCAG=ut6+TN52NUdhC4ByWp02ccWGgOUq_2WLek+M2Q-M0zAmKag@mail.gmail.com%3E

br.
Julli

**Comment by danhaywood** [comment]
We've just bumped Estatio to use Isis 1.13.0, so try again.

**Comment by jullimullins** [comment]
Thank you!
