### ISSUE TITLE
Is there a default Database being installed?

### ISSUE THREAD

**Issue by nass999** [estatio/estatio#53]
I have successfully installed on my local machine using Maven. Is there a default DB being installed?

**Comment by johandoornenbal** [comment]
The current config file (1) tells the framework (Apache Isis) to use an in-memory db. This works for demo / testing. We recommend using Postgre for production when using OS.
More information you find on (2)

(1)
https://github.com/estatio/estatio/blob/master/estatioapp/webapp/src/main/webapp/WEB-INF/persistor.properties#L27

(2)
http://isis.apache.org/guides/rgcfg.html#3.-configuration-files
http://isis.apache.org/guides/ugbtb.html#6.-datanucleus
