### ISSUE TITLE
Production use cases and reference architectures

### ISSUE THREAD

**Issue by nass999** [estatio/estatio#54]
Are there any active production use cases - especially in cloud? Is EuroCommercial a sponsor of this project?

**Comment by johandoornenbal** [comment]
To my knowledge there are no production cases in the cloud. EuroCommercial runs Estatio in their private environment and is indeed sponsor of the project.

**Comment by danhaywood** [comment]
For a little more information on Estatio, see the [Powered-by]http://isis.apache.org/powered-by.html#_powered-by_estatio) page on the Apache Isis website.

While Estatio is open source - and makes for a fantastic demonstation of the capabilities of the Apache Isis framework - we don't expect it to be usable "as is" by other parties: it is specific to the way that EuroCommercial conducts its business, other companies we would imagine do things differently.

You can of course fork it and adapt it, and we are also pulling out generic modules that can be reused in other applications - see the [Incode Catalog](http://catalog.incode.org/) (business functionality) and the [IsisAddons](http://www.isisaddons.org/) (technical functionality.
