### ISSUE TITLE
Build Fails with DskipTests

### ISSUE THREAD

**Issue by andrenventer** [estatio/estatio#57]
Ubuntu 16.04.1 x64
JDK 8

mvn clean install -T1C -o -DskipTests=true || exit 1  >/dev/null

---

[INFO] Building Incode Module Communications DOM 1.8.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Estatio (Open Source) .............................. SUCCESS [  1.244 s]
[INFO] Estatio (Open Source) UDO Base ..................... SUCCESS [ 13.107 s]
[INFO] Estatio (Open Source) UDO DOM - Tax ................ SUCCESS [  4.113 s]
[INFO] Estatio (Open Source) UDO DOM - Charge ............. SKIPPED
[INFO] Estatio (Open Source) UDO DOM - Currency ........... SUCCESS [  3.049 s]
[INFO] Estatio (Open Source) UDO DOM - Numerator .......... SUCCESS [  2.551 s]
[INFO] Estatio (Open Source) UDO DOM - Event .............. SUCCESS [  3.171 s]
[INFO] Estatio (Open Source) UDO DOM - Index .............. SUCCESS [  2.996 s]
[INFO] Estatio (Open Source) UDO DOM - Link ............... SUCCESS [  2.685 s]
[INFO] Incode Module Communications DOM ................... FAILURE [  0.187 s]
[INFO] Estatio (Open Source) UDO DOM - Party and Agreement  SKIPPED
[INFO] Estatio (Open Source) UDO DOM - Project ............ SKIPPED
[INFO] Estatio (Open Source) UDO DOM - Settings ........... SKIPPED
[INFO] Estatio (Open Source) DOM & Services ............... SKIPPED
[INFO] Estatio (Open Source) Import Managers .............. SKIPPED
[INFO] Estatio (Open Source) Fixtures ..................... SKIPPED
[INFO] Estatio (Open Source) App .......................... SKIPPED
[INFO] Estatio (Open Source) Integration Tests ............ SKIPPED
[INFO] Estatio (Open Source) Webapp ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.055 s
[INFO] Finished at: 2016-10-26T20:25:07+00:00
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Estatio (Open Source) UDO DOM - Settings
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Estatio (Open Source) UDO DOM - Charge
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] Final Memory: 53M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project incode-module-communications-dom: Could not resolve dependencies for project org.incode.module.communications:incode-module-communications-dom:jar:1.8.0-SNAPSHOT: Cannot access snapshots-repo (http://repository-estatio.forge.cloudbees.com/snapshot/) in offline mode and the artifact com.google:rfc-2445:jar:1.0-20150303.092731-1 has not been downloaded from it before. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :incode-module-communications-dom

**Comment by danhaywood** [comment]
It's necessary to install the rfc-2445.jar manually, I think (it isn't available in maven central repo).

**Comment by andrenventer** [comment]
OK Thanks Dan :)

**Comment by weddingjuma** [comment]
hi, @andrenventer. did you manage to install estatio, I am facing the same problem

**Comment by weddingjuma** [comment]
Thanks I  workaround it, by disabling the tests using -DskipTests.  use    mvn clean install -DskipTests  instead of   mvn clean install

But am still looking forward for a better solution

**Comment by danhaywood** [comment]
What tests are failing if you omit -DskipTests ?

**Comment by andrenventer** [comment]
Does it build now, Dan?

**Comment by danhaywood** [comment]
Yes.

But if you are still having issues and want to do a join TeamViewer session at some point, then contact me via email.

Cheers
Dan
