### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by andrenventer** [estatio/estatio#58]
Progress after previous attempts:

This time followed steps below on
ubuntu-512mb-ams3-01 512 MB Memory / 20 GB Disk / AMS3 - Ubuntu 16.04.1 x64

sudo apt-get update
sudo apt-get install default-jdk
sudo update-alternatives --config java
sudo nano /etc/environment
JAVA_HOME="YOUR_PATH"
source /etc/environment
echo $JAVA_HOME
sudo apt-get install maven
git clone https://github.com/jcvanderwal/google-rfc-2445.git
cd google-rfc-2445/
git checkout mavenized
mvn clean install -DskipTests
cd ../
git clone https://github.com/estatio/estatio.git
cd estatio
mvn clean install -Pjetty-console

Running org.estatio.dom.base.SortedSetsContractTestAll
org.estatio.dom.agreement.Agreement
  processing Agreement#roles
org.estatio.dom.agreement.AgreementForTesting
  processing AgreementForTesting#roles
org.estatio.dom.agreement.AgreementRole
  processing AgreementRole#communicationChannels
org.estatio.dom.agreement.AgreementRoleCommunicationChannel
org.estatio.dom.agreement.AgreementRoleCommunicationChannelType
org.estatio.dom.agreement.AgreementRoleType
org.estatio.dom.agreement.AgreementTest$ChangeDates$1
  processing #roles
org.estatio.dom.agreement.AgreementTest$FindParty$AgreementForSubtypeTesting
  processing AgreementForSubtypeTesting#roles
org.estatio.dom.agreement.AgreementTest$NewRole$Defaults$1
  processing #roles
org.estatio.dom.agreement.AgreementType
org.estatio.dom.asset.CommunicationChannelOwnerLinkForFixedAsset
org.estatio.dom.asset.FixedAsset
  processing FixedAsset#roles
  processing FixedAsset#owners
org.estatio.dom.asset.FixedAssetForTesting
  processing FixedAssetForTesting#roles
  processing FixedAssetForTesting#owners
org.estatio.dom.asset.FixedAssetRegistrationTest$BeanProperties$1
org.estatio.dom.asset.FixedAssetRole
org.estatio.dom.asset.Property
  processing Property#roles
  processing Property#units
  processing Property#owners
org.estatio.dom.asset.Unit
  processing Unit#roles
  processing Unit#owners
org.estatio.dom.asset.UnitTest$BeanProperties$1
  processing #roles
  processing #owners
org.estatio.dom.asset.financial.FixedAssetFinancialAccount
org.estatio.dom.asset.ownership.FixedAssetOwnership
org.estatio.dom.asset.paperclips.PaperclipForFixedAsset
org.estatio.dom.asset.registration.FixedAssetRegistration
org.estatio.dom.asset.registration.FixedAssetRegistrationContributionsTest$NewRegistration$FoobarAssetRegistration
org.estatio.dom.asset.registration.FixedAssetRegistrationForTesting
org.estatio.dom.asset.registration.FixedAssetRegistrationType
org.estatio.dom.bankmandate.BankMandate
  processing BankMandate#roles
org.estatio.dom.budgetassignment.BudgetAssignmentServiceTest$2
org.estatio.dom.budgetassignment.BudgetAssignmentServiceTest$3
org.estatio.dom.budgetassignment.BudgetCalculationLink
org.estatio.dom.budgetassignment.BudgetCalculationLinkForTesting
org.estatio.dom.budgetassignment.ServiceChargeItem
org.estatio.dom.budgeting.ChargeForTesting
org.estatio.dom.budgeting.CurrencyForTesting
org.estatio.dom.budgeting.PropertyForTesting
  processing PropertyForTesting#roles
  processing PropertyForTesting#units
  processing PropertyForTesting#owners
org.estatio.dom.budgeting.UnitForTesting
  processing UnitForTesting#roles
  processing UnitForTesting#owners
org.estatio.dom.budgeting.allocation.BudgetItemAllocation
org.estatio.dom.budgeting.budget.Budget
  processing Budget#keyTables
  processing Budget#items
org.estatio.dom.budgeting.budget.BudgetForTesting
  processing BudgetForTesting#keyTables
  processing BudgetForTesting#items
org.estatio.dom.budgeting.budgetcalculation.BudgetCalculation
org.estatio.dom.budgeting.budgetitem.BudgetItem
  processing BudgetItem#budgetItemAllocations
org.estatio.dom.budgeting.budgetitem.BudgetItemForTesting
  processing BudgetItemForTesting#budgetItemAllocations
org.estatio.dom.budgeting.keyitem.KeyItem
org.estatio.dom.budgeting.keyitem.KeyItemForTesting
org.estatio.dom.budgeting.keytable.KeyTable
  processing KeyTable#items
org.estatio.dom.budgeting.keytable.KeyTableForTesting
  processing KeyTableForTesting#items
org.estatio.dom.charge.Charge
org.estatio.dom.charge.ChargeGroup
  processing ChargeGroup#charges
org.estatio.dom.currency.Currency
org.estatio.dom.event.Event
org.estatio.dom.event.EventSourceLink
org.estatio.dom.financial.FinancialAccount
org.estatio.dom.financial.FinancialAccountTest$CompareTo$1
org.estatio.dom.financial.FinancialAccountTransaction
org.estatio.dom.financial.bankaccount.BankAccount
org.estatio.dom.guarantee.Guarantee
  processing Guarantee#roles
org.estatio.dom.index.Index
  processing Index#indexBases
org.estatio.dom.index.IndexBase
  processing IndexBase#values
org.estatio.dom.index.IndexValue
org.estatio.dom.invoice.Invoice
  processing Invoice#items
org.estatio.dom.invoice.InvoiceItem
org.estatio.dom.invoice.InvoiceItemForTesting
org.estatio.dom.invoice.InvoiceItemTest$Verify$2
org.estatio.dom.invoice.InvoiceRepositoryTest$1
  processing #breakOptions
  processing #occupancies
  processing #roles
  processing #items
org.estatio.dom.invoice.InvoiceTest$4$1
  processing #items
org.estatio.dom.invoice.InvoiceTest$5
  processing #items
org.estatio.dom.invoice.InvoiceTest$Collect$1
  processing #items
org.estatio.dom.invoice.InvoiceTest$Collect$2$1
  processing #roles
org.estatio.dom.invoice.InvoiceTest$Collect$2$1$1
org.estatio.dom.invoice.InvoiceTest$ValidInvoiceDate$1
  processing #items
org.estatio.dom.invoice.paperclips.PaperclipForInvoice
org.estatio.dom.invoice.viewmodel.InvoiceSummaryForInvoiceRun
org.estatio.dom.invoice.viewmodel.InvoiceSummaryForPropertyDueDateStatus
org.estatio.dom.invoice.viewmodel.InvoiceSummaryForPropertyInvoiceDate
org.estatio.dom.lease.Lease
  processing Lease#breakOptions
  processing Lease#occupancies
  processing Lease#roles
  processing Lease#items
org.estatio.dom.lease.LeaseForTest
  processing LeaseForTest#breakOptions
  processing LeaseForTest#occupancies
  processing LeaseForTest#roles
  processing LeaseForTest#items
org.estatio.dom.lease.LeaseItem
  processing LeaseItem#terms
org.estatio.dom.lease.LeaseItemSource
org.estatio.dom.lease.LeaseItemTest$ChangeDates$1
  processing #terms
org.estatio.dom.lease.LeaseItemTest$ChoicesNewSourceItem$1
  processing #breakOptions
  processing #occupancies
  processing #roles
  processing #items
org.estatio.dom.lease.LeaseItemTest$GetCurrentValue$2
  processing #terms
org.estatio.dom.lease.LeaseItemTest$Remove$1
  processing #invoiceItems
org.estatio.dom.lease.LeaseTerm
  processing LeaseTerm#invoiceItems
org.estatio.dom.lease.LeaseTermForDeposit
  processing LeaseTermForDeposit#invoiceItems
org.estatio.dom.lease.LeaseTermForDepositTest$1
  processing #terms
org.estatio.dom.lease.LeaseTermForDepositTest$ValueForDate$1
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermForDepositTest$ValueForDate$2
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermForFixed
  processing LeaseTermForFixed#invoiceItems
org.estatio.dom.lease.LeaseTermForIndexable
  processing LeaseTermForIndexable#invoiceItems
org.estatio.dom.lease.LeaseTermForPercentage
  processing LeaseTermForPercentage#invoiceItems
org.estatio.dom.lease.LeaseTermForServiceCharge
  processing LeaseTermForServiceCharge#invoiceItems
org.estatio.dom.lease.LeaseTermForTax
  processing LeaseTermForTax#invoiceItems
org.estatio.dom.lease.LeaseTermForTaxTest$ChangeInvoice$1
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermForTaxTest$ChangeTax$1
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermForTaxTest$DoAlign$1
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermForTaxTest$DoAlign$2
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermForTesting
  processing LeaseTermForTesting#invoiceItems
org.estatio.dom.lease.LeaseTermForTurnoverRent
  processing LeaseTermForTurnoverRent#invoiceItems
org.estatio.dom.lease.LeaseTermTest$ChangeDates$1
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermTest$ChangeDates$2
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermTest$ChangeDatesDelegate$1
  processing #invoiceItems
org.estatio.dom.lease.LeaseTermTest$ChangeDatesDelegate$2
  processing #invoiceItems
org.estatio.dom.lease.LeaseTest$ChangePaymentMethodForAll$1
  processing #breakOptions
  processing #occupancies
  processing #roles
  processing #items
org.estatio.dom.lease.LeaseTest$NewMandate$8
  processing #agreements
  processing #registrations
org.estatio.dom.lease.LeaseTest$RenewKeepingThis$1
  processing #breakOptions
  processing #occupancies
  processing #roles
  processing #items
org.estatio.dom.lease.LeaseType
org.estatio.dom.lease.Occupancy
org.estatio.dom.lease.OccupancyTest$ChangeDates$1
org.estatio.dom.lease.assignment.LeaseAssignment
org.estatio.dom.lease.breaks.BreakOption
org.estatio.dom.lease.breaks.EventSourceLinkForBreakOption
org.estatio.dom.lease.breaks.FixedBreakOption
org.estatio.dom.lease.breaks.RollingBreakOption
org.estatio.dom.lease.invoicing.InvoiceCalculationParametersTest$ToString$1
  processing #breakOptions
  processing #occupancies
  processing #roles
  processing #items
org.estatio.dom.lease.invoicing.InvoiceCalculationParametersTest$ToString$2
  processing #terms
org.estatio.dom.lease.invoicing.InvoiceCalculationParametersTest$ToString$3
  processing #invoiceItems
org.estatio.dom.lease.invoicing.InvoiceItemForLease
org.estatio.dom.lease.tags.Activity
org.estatio.dom.lease.tags.Brand
org.estatio.dom.lease.tags.Sector
  processing Sector#activities
org.estatio.dom.lease.tags.UnitSize
org.estatio.dom.numerator.Numerator
org.estatio.dom.party.CommunicationChannelOwnerLinkForParty
org.estatio.dom.party.Organisation
  processing Organisation#agreements
  processing Organisation#registrations
  processing Organisation#previousNames
org.estatio.dom.party.OrganisationPreviousName
org.estatio.dom.party.Party
  processing Party#agreements
  processing Party#registrations
org.estatio.dom.party.PartyForTesting
  processing PartyForTesting#agreements
  processing PartyForTesting#registrations
org.estatio.dom.party.PartyRegistration
org.estatio.dom.party.PartyRegistrationTest$ChangeDates$1
org.estatio.dom.party.PartyRepositoryTest$ValidateNewParty$1$1
  processing #agreements
  processing #registrations
org.estatio.dom.party.Person
  processing Person#agreements
  processing Person#registrations
org.estatio.dom.party.paperclips.PaperclipForParty
org.estatio.dom.party.relationship.PartyRelationship
org.estatio.dom.project.BusinessCase
org.estatio.dom.project.BusinessCaseForTesting
org.estatio.dom.project.Program
  processing Program#roles
org.estatio.dom.project.ProgramForTesting
  processing ProgramForTesting#roles
org.estatio.dom.project.ProgramRole
org.estatio.dom.project.Project
  processing Project#roles
org.estatio.dom.project.ProjectForTesting
  processing ProjectForTesting#roles
org.estatio.dom.project.ProjectRole
org.estatio.dom.tax.Tax
  processing Tax#rates
org.estatio.dom.tax.TaxRate
DONE
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.767 sec - in org.estatio.dom.base.SortedSetsContractTestAll
Running org.estatio.dom.base.WithReferenceUniqueContractForEstatioTest_hasJdoUniqueIndexAnnotation
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.932 sec - in org.estatio.dom.base.WithReferenceUniqueContractForEstatioTest_hasJdoUniqueIndexAnnotation
Running org.estatio.dom.base.WithNameComparableContractForEstatioTest_compareTo
Killed

**Comment by danhaywood** [comment]
Not sure what the issue is here... all I see at the end is "Killed" but no other info,

I appreciate you've raised a bunch of issues here, but the code does build fine for us and in our CI...

Meantime, I have updated the README.adoc regarding the google rfc-2445 jar, because this didn't seem to be documented anywhere publicly.

Thx
Dan
