### ISSUE TITLE
Build Fails with DskipTests

### ISSUE THREAD

**Issue by andrenventer** [estatio/estatio#59]
Steps followed on:
ubuntu-512mb-ams3-01 512 MB Memory / 20 GB Disk / AMS3 - Ubuntu 16.04.1 x64

sudo apt-get update
sudo apt-get install default-jdk
sudo update-alternatives --config java
sudo nano /etc/environment
JAVA_HOME="YOUR_PATH"
source /etc/environment
echo $JAVA_HOME
sudo apt-get install maven
git clone https://github.com/jcvanderwal/google-rfc-2445.git
cd google-rfc-2445/
git checkout mavenized
mvn clean install -DskipTests
cd ../
git clone https://github.com/estatio/estatio.git
cd estatio
mvn clean install -T1C -o -DskipTests=true || exit 1 >/dev/null

[INFO] Reactor Summary:
[INFO] 
[INFO] Estatio (Open Source) .............................. SUCCESS [  1.282 s]
[INFO] Estatio (Open Source) UDO Base ..................... SUCCESS [ 15.152 s]
[INFO] Estatio (Open Source) UDO DOM - Tax ................ SUCCESS [  5.222 s]
[INFO] Estatio (Open Source) UDO DOM - Charge ............. SUCCESS [  3.670 s]
[INFO] Estatio (Open Source) UDO DOM - Currency ........... SUCCESS [  4.303 s]
[INFO] Estatio (Open Source) UDO DOM - Numerator .......... SUCCESS [  2.818 s]
[INFO] Estatio (Open Source) UDO DOM - Event .............. SUCCESS [  3.738 s]
[INFO] Estatio (Open Source) UDO DOM - Index .............. SUCCESS [  3.341 s]
[INFO] Estatio (Open Source) UDO DOM - Link ............... SUCCESS [  2.435 s]
[INFO] Incode Module Communications DOM ................... SUCCESS [  9.279 s]
[INFO] Estatio (Open Source) UDO DOM - Party and Agreement  SUCCESS [  8.456 s]
[INFO] Estatio (Open Source) UDO DOM - Project ............ SUCCESS [  5.180 s]
[INFO] Estatio (Open Source) UDO DOM - Settings ........... SUCCESS [  2.700 s]
[INFO] Estatio (Open Source) DOM & Services ............... FAILURE [ 41.338 s]
[INFO] Estatio (Open Source) Import Managers .............. SKIPPED
[INFO] Estatio (Open Source) Fixtures ..................... SKIPPED
[INFO] Estatio (Open Source) App .......................... SKIPPED
[INFO] Estatio (Open Source) Integration Tests ............ SKIPPED
[INFO] Estatio (Open Source) Webapp ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:55 min
[INFO] Finished at: 2016-10-28T16:48:45+00:00
[INFO] Final Memory: 52M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.isis.tool:isis-maven-plugin:1.13.0.20160930-1554:validate (default) on project estatio-dom: Execution default of goal org.apache.isis.tool:isis-maven-plugin:1.13.0.20160930-1554:validate failed: Plugin org.apache.isis.tool:isis-maven-plugin:1.13.0.20160930-1554 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.reflections:reflections:jar:0.9.10, org.hsqldb:hsqldb:jar:2.3.1, joda-time:joda-time:jar:2.9.1, org.apache.maven:maven-plugin-api:jar:3.0.5, org.codehaus.plexus:plexus-utils:jar:2.1, org.apache.maven:maven-core:jar:3.0.5, org.apache.maven:maven-model:jar:3.0.5, org.apache.maven:maven-model-builder:jar:3.0.5, org.apache.maven:maven-settings:jar:3.0.5, org.apache.maven:maven-artifact:jar:3.0.5, org.apache.maven:maven-project:jar:3.0-alpha-2, org.apache.maven:maven-compat:jar:3.0.5, junit:junit:jar:4.12, org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3, org.sonatype.plexus:plexus-cipher:jar:1.4, org.apache.maven:maven-toolchain:jar:3.0-alpha-2: Cannot access estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/) in offline mode and the artifact org.reflections:reflections:jar:0.9.10 has not been downloaded from it before. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :estatio-dom

**Comment by danhaywood** [comment]
The error message states:

> Cannot  access estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/) in offline mode

So, don't include "-o" in the mvn command.
