### ISSUE TITLE
Estatio postgresql Installation

### ISSUE THREAD

**Issue by weddingjuma** [estatio/estatio#60]
I am trying to install estatio on a postgresql  server but unsuccessfull. 
     suppose my the database user is : steve
                             password: steve
                       the server ip 123.122.123.124,

 are the below setting right for postgresql. 
May I also know if should I create the database estatio or it will be created automatically 

isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionDriverName=org.postgresql.Driver
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionURL=jdbc:postgresql://123.122.123.124:5432/estatio
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionUserName=steve
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionPassword=steve

**Comment by danhaywood** [comment]
On PostgreSQL, IIRC, you need to create the 'estatio' database first, then
grant permissions for the user/password specified.

If that doesn't work for you, perhaps you could post the stacktrace/some
further details ?

Thx
Dan
