### ISSUE TITLE
Accounting Schema

### ISSUE THREAD

**Issue by nass999** [estatio/estatio#73]
Would anyone have an idea of what the accounting backend/tables look like? Would they be using accrual based accounting or cash accounting?

**Comment by danhaywood** [comment]
We use Apache Camel (and the isisaddons' publishmq module) to call the SOAP endpoints of a general ledger application.  I'm afraid after that it's a black box to me.  I don't think there are any assumptions within Estatio as to how you do the accounting, though.

If you do a retro-run of invoices, it will create delta InvoiceItems if there was a change in circumstance for the tenant to be accounted for.  Any previously invoiced Invoice/InvoiceItems are immutable; a new retrospective Invoice is created to contain such deltas.

HTH
Dan
