### ISSUE TITLE
error when building estatio 

### ISSUE THREAD

**Issue by carladelmonte** [estatio/estatio#8]
When building Estatio I received the following error: 
Failed to execute goal on project udo-dom-tax: Could not resolve dependencies for project org.estatio:udo-dom-tax:jar:1.2.0-SNAPSHOT: Failure to find org.estatio:udo-base:jar:tests:1.2.0-20150129.084813-38 in http://repository-estatio.forge.cloudbees.com/snapshot/
Since I'm a novice on this matter how can I resolve the right dependencies for the project. I've noticed that the udo-dom-tax has changed on Febr. 2. 
Krgrds, Carla

**Comment by danhaywood** [comment]
Hi Carla,
Thanks for taking the time to look at Estatio.

Um, in general the app should "just build", though we are running against
Isis 1.8.0-SNAPSHOT (ie latest-n-greatest) and occasionally there are
hiccups.

You could try this:
- delete the contents of ~/.m2/repository/org/apache/isis
- delete the contents of ~/.m2/repository/org/estatio

Get the latest version of Estatio once more (git pull)

Do a build as normal, "mvn clean install".

This should cause mvn to download the latest version of Isis, and hopefully
your issue will go away...

Let us know

Dan

**Comment by carladelmonte** [comment]
Hi Dan,

To have a fallback I renamed the ~/.m2 files and did a clean install. No errors on the Isis build but on the Estatio build.
The error is as follows:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project udo-base: There are test failures.

Failed tests: 
  PojoTesterTest_interference.strict_whenInterferenceBetweenProperties 
Expected: exception with message a string containing "lastName: setLastName interferes with getFirstName"
     but: message was "firstName: Test failed for firstName using string3"
Stacktrace was: junit.framework.AssertionFailedError: firstName: Test failed for firstName using string3

Btw do you have a demo site of Estatio where you the application "in action"?

Krgrds Carla

**Comment by martin-g** [comment]
I have just pulled latest Estatio, branch `master` and the build is OK here.
I have also tried with different locale (DE) and the tests still pass here.

**Comment by carladelmonte** [comment]
Hi Martin,
I did a clean install but it build Estatio with an error.  As a test I ran the Isis simpleapp-webapp. That worked ok.
What OS, Java, Maven are you using? Perhaps there are some minors differences on what I'm working with. 
My versions are:
versions:
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/local/apache-maven-3.2.5
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: nl_NL, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"

java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
 
Krgds Carla

**Comment by danhaywood** [comment]
Use Java 7, not Java 8; that could well be the issue.  At any rate, Isis
itself does not yet support Java 8 (we need to upgrade our dependency on
DataNucleus, something we'll be doing pretty soon now...).

For myself, I'm on:
- win 8.1
- Java 1.7_0_45
- Maven 3.2.3

Martin is on Ubuntu.

And Jeroen works on both Windows and a Mac.

**Comment by carladelmonte** [comment]
Hi Dan,

I better wait for that. Mac OS itself has a different Java version then the installed JDK.  Some of my installed apps depend on these installed java versions.
Btw I could run the Isis simple-webapp with the Java 8 installed.

Thanks for your reply and I await the upgrade.

Krgrds Carla

> Op 3 feb. 2015, om 19:12 heeft Dan Haywood <notifications@github.com> het volgende geschreven:
> 
> Use Java 7, not Java 8; that could well be the issue. At any rate, Isis 
> itself does not yet support Java 8 (we need to upgrade our dependency on 
> DataNucleus, something we'll be doing pretty soon now...). 
> 
> For myself, I'm on: 
> - win 8.1 
> - Java 1.7_0_45 
> - Maven 3.2.3 
> 
> Martin is on Ubuntu. 
> 
> And Jeroen works on both Windows and a Mac. 
> 
>

**Comment by carladelmonte** [comment]
Update:
I have a workaround for the error message. When you install Estatio by using Maven, Maven runs some unit-tests. When you add the parameter "mvn install -DskipTests" Maven builds Estatio without testing. Not ideal of course but if it is a minor error you can use this. Otherwise there has some debugging to be done.

**Comment by danhaywood** [comment]
Could you post some details of the failing tests?  Look in
target/surefire-reports for the failing module.

Thx
Dan

**Comment by carladelmonte** [comment]
Hi Dan,

Hereby you receive the files as attachments:

Rgds Carla


> Op 3 feb. 2015, om 21:14 heeft Dan Haywood <notifications@github.com> het volgende geschreven:
> 
> Could you post some details of the failing tests? Look in 
> target/surefire-reports for the failing module. 
> 
> Thx 
> Dan 
> 
> On 3 February 2015 at 20:08, carladelmonte <notifications@github.com> wrote: 
> 
> > Update: 
> > I have a workaround for the error message. When you install Estatio by 
> > using Maven, Maven runs some unit-tests. When you add the parameter "mvn 
> > install -DskipTests" Maven builds Estatio without testing. Not ideal of 
> > course but if it is a minor error you can use this. Otherwise there has 
> > some debugging to be done. 
> > 
> > — 
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/estatio/estatio/issues/8#issuecomment-72724336>. 
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/estatio/estatio/issues/8#issuecomment-72725232>.
> 
-------------------------------------------------------------------------------
Test set: org.estatio.dom.PojoTesterTest_interference
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec <<< FAILURE! - in org.estatio.dom.PojoTesterTest_interference
strict_whenInterferenceBetweenProperties(org.estatio.dom.PojoTesterTest_interference)  Time elapsed: 0.034 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: exception with message a string containing "lastName: setLastName interferes with getFirstName"
     but: message was "firstName: Test failed for firstName using string3"
Stacktrace was: junit.framework.AssertionFailedError: firstName: Test failed for firstName using string3
	at org.estatio.dom.PojoTester.handleExceptions(PojoTester.java:301)
	at org.estatio.dom.PojoTester.exercise(PojoTester.java:285)
	at org.estatio.dom.PojoTester.exercise(PojoTester.java:258)
	at org.estatio.dom.PojoTesterTest_interference.strict_whenInterferenceBetweenProperties(PojoTesterTest_interference.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.estatio.dom.PojoTester$TestException: Test failed for firstName using string3
	at org.estatio.dom.PojoTester.invokeSetterAndGetter(PojoTester.java:449)
	at org.estatio.dom.PojoTester.exercise(PojoTester.java:386)
	at org.estatio.dom.PojoTester.testOne(PojoTester.java:324)
	at org.estatio.dom.PojoTester.exercise(PojoTester.java:278)
	... 27 more

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:198)
	at org.junit.rules.ExpectedException.optionallyHandleException(ExpectedException.java:190)
	at org.junit.rules.ExpectedException.access$300(ExpectedException.java:85)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:175)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by danhaywood** [comment]
ok, thanks... this is definitely a Java8 issue.  Rather trivial, we have a
contract unit test that is using the reflection APIs and I guess they are
returned in a different order.

If you put an @Ignore on that failing test (PojoTesterTest_interference),
do any others fail also?

thx

**Comment by carladelmonte** [comment]
Could you help me out on this one? (This is not my daily job :) ). What do I type in the command line?
thx

> Op 3 feb. 2015, om 21:47 heeft Dan Haywood <notifications@github.com> het volgende geschreven:
> 
> ok, thanks... this is definitely a Java8 issue. Rather trivial, we have a 
> contract unit test that is using the reflection APIs and I guess they are 
> returned in a different order. 
> 
> If you put an @Ignore on that failing test (PojoTesterTest_interference), 
> do any others fail also? 
> 
> thx 
> 
> 
>

**Comment by danhaywood** [comment]
Locate this file:
https://github.com/estatio/estatio/blob/master/udo/base/dom/src/test/java/org/estatio/dom/PojoTesterTest_interference.java#L70

and add

@org.junit.Ignore

before the @Test

~~~
but if this doesn't go through cleanly, we'll stop at this point; I'm sure
you don't want to spend all evening debugging this (nor do I).  I can dust
off my Macbook to look into it more thoroughly.



On 3 February 2015 at 20:53, carladelmonte <notifications@github.com> wrote:

> Could you help me out on this one? (This is not my daily job :) ). What do
> I type in the command line?
> thx
>
> > Op 3 feb. 2015, om 21:47 heeft Dan Haywood <notifications@github.com>
> het volgende geschreven:
> >
> > ok, thanks... this is definitely a Java8 issue. Rather trivial, we have
> a
> > contract unit test that is using the reflection APIs and I guess they
> are
> > returned in a different order.
> >
> > If you put an @Ignore on that failing test
> (PojoTesterTest_interference),
> > do any others fail also?
> >
> > thx
> >
> >
> >
> > On 3 February 2015 at 20:26, carladelmonte <notifications@github.com>
> wrote:
> >
> > > Hi Dan,
> > >
> > > Hereby you receive the files as attachments:
> > >
> > > Rgds Carla
> > >
> > >
> > > > Op 3 feb. 2015, om 21:14 heeft Dan Haywood <notifications@github.com>
>
> > > het volgende geschreven:
> > > >
> > > > Could you post some details of the failing tests? Look in
> > > > target/surefire-reports for the failing module.
> > > >
> > > > Thx
> > > > Dan
> > > >
> > > > On 3 February 2015 at 20:08, carladelmonte <notifications@github.com>
>
> > > wrote:
> > > >
> > > > > Update:
> > > > > I have a workaround for the error message. When you install
> Estatio by
> > > > > using Maven, Maven runs some unit-tests. When you add the
> parameter
> > > "mvn
> > > > > install -DskipTests" Maven builds Estatio without testing. Not
> ideal
> > > of
> > > > > course but if it is a minor error you can use this. Otherwise
> there
> > > has
> > > > > some debugging to be done.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/estatio/estatio/issues/8#issuecomment-72724336>.
>
> > > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > https://github.com/estatio/estatio/issues/8#issuecomment-72725232>.
> > > >
> > >
> -------------------------------------------------------------------------------
>
> > >
> > > Test set: org.estatio.dom.PojoTesterTest_interference
> > >
> -------------------------------------------------------------------------------
>
> > >
> > > Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.054
> sec
> > > <<< FAILURE! - in org.estatio.dom.PojoTesterTest_interference
> > >
> strict_whenInterferenceBetweenProperties(org.estatio.dom.PojoTesterTest_interference)
>
> > > Time elapsed: 0.034 sec <<< FAILURE!
> > > java.lang.AssertionError:
> > > Expected: exception with message a string containing "lastName:
> > > setLastName interferes with getFirstName"
> > > but: message was "firstName: Test failed for firstName using string3"
> > > Stacktrace was: junit.framework.AssertionFailedError: firstName: Test
> > > failed for firstName using string3
> > > at org.estatio.dom.PojoTester.handleExceptions(PojoTester.java:301)
> > > at org.estatio.dom.PojoTester.exercise(PojoTester.java:285)
> > > at org.estatio.dom.PojoTester.exercise(PojoTester.java:258)
> > > at
> > >
> org.estatio.dom.PojoTesterTest_interference.strict_whenInterferenceBetweenProperties(PojoTesterTest_interference.java:73)
>
> > >
> > > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > > at
> > >
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>
> > >
> > > at
> > >
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>
> > >
> > > at java.lang.reflect.Method.invoke(Method.java:483)
> > > at
> > >
> org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
>
> > >
> > > at
> > >
> org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>
> > >
> > > at
> > >
> org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
>
> > >
> > > at
> > >
> org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
>
> > >
> > > at
> > >
> org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
>
> > >
> > > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> > > at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
> > > at
> > >
> org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
>
> > >
> > > at
> > >
> org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
>
> > >
> > > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> > > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> > > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> > > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> > > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> > > at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> > > at
> > >
> org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> > > Caused by: org.estatio.dom.PojoTester$TestException: Test failed for
> > > firstName using string3
> > > at
> org.estatio.dom.PojoTester.invokeSetterAndGetter(PojoTester.java:449)
> > > at org.estatio.dom.PojoTester.exercise(PojoTester.java:386)
> > > at org.estatio.dom.PojoTester.testOne(PojoTester.java:324)
> > > at org.estatio.dom.PojoTester.exercise(PojoTester.java:278)
> > > ... 27 more
> > >
> > > at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
> > > at org.junit.Assert.assertThat(Assert.java:865)
> > > at org.junit.Assert.assertThat(Assert.java:832)
> > > at
> > >
> org.junit.rules.ExpectedException.handleException(ExpectedException.java:198)
>
> > >
> > > at
> > >
> org.junit.rules.ExpectedException.optionallyHandleException(ExpectedException.java:190)
>
> > >
> > > at
> org.junit.rules.ExpectedException.access$300(ExpectedException.java:85)
> > > at
> > >
> org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:175)
>
> > >
> > > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> > > at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
> > > at
> > >
> org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
>
> > >
> > > at
> > >
> org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
>
> > >
> > > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> > > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> > > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> > > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> > > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> > > at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> > > at
> > >
> org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>
> > >
> > > at
> > >
> org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/estatio/estatio/issues/8#issuecomment-72727453>.
> > >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/estatio/estatio/issues/8#issuecomment-72731217>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/estatio/estatio/issues/8#issuecomment-72732438>.
>

**Comment by martin-g** [comment]
@carladelmonte You can use something like https://github.com/martin-g/dotfiles/blob/master/bin/mvn6
This is a short shell script that temporarily/locally exports JDK 1.6 for the current Maven execution.

I guess you can do something similar to export JDK 1.7 just for Estatio with `/usr/libexec/java_home`

**Comment by carladelmonte** [comment]
@danhaywood 
I added @org.junit.Ignore before the @Test. Estatio build well. (Accept I ran into a disk space error, but that had nothing to do with Estatio)
@martin-g 
Prior to the errors, I've tried it with the JDK 1.6 (that is the Mac version) and the build failed. Surprisingly it works with JDK 1.8 (without the unit tests). I'll give it a try tomorrow with the JDK 1.7

**Comment by mnesarco** [comment]
Hi,
I have checked out the latest, but it does not build with java7:

    Detected JDK Version: 1.7.0-67 is not in the allowed range [1.8.0,).

So I have changed to java8 and it builds ok (isis and estatio) but estatio does not start:

    java.lang.RuntimeException: Error scanning entry org/estatio/dom/IsisMultilineLines.class from jar file:/tmp/estatio-webapp-1.2.0-SNAPSHOT-jetty-console.war_8080/webapp/WEB-INF/lib/udo-base-1.2.0-SNAPSHOT.jar

This error appears for every dom class.

**Comment by danhaywood** [comment]
The first error you had isn't really an error... we use the
maven-enforcer-plugin to require that JDK8 is used for Estatio.

The second error though is very peculiar... not seen that issue before.
Almost looks like a corruption in some jar file.

I know it's a bit lame to suggest, but perhaps you might try deleting
~/.m2/repository/org/apache/isis and ~/.m2/repository/org/estatio and then
try building Estatio again?

Thx
Dan
