### ISSUE TITLE
fixtures exception

### ISSUE THREAD

**Issue by jintonghuoya** [estatio/estatio#84]
![image](https://user-images.githubusercontent.com/11802095/34906367-4d6ddb94-f8a7-11e7-91b6-f30983dc601c.png)
And I come from china,our country can not access www.google.com url.I dont know if there is something wrong with this.

**Comment by vpoluyaktov** [comment]
I have the same issue
I'm from US so google.com is not a problem 
It looks like the fixture scripts are just missing

**Comment by jintonghuoya** [comment]
I have already fix this bugs.
You should put the fixtures in the right packge.
